apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Release WF
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in application releases. Refer to https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest for the expected format
metadata:
  stages/v1alpha1:
    - name: DEV
      jobs:
        - DEV
        - Approve
    - name: STAGING
      jobs:
        - STAGING
    - name: PROD
      jobs:
        - PROD
jobs:
  DEV:
    environment: DEV
    uses: ./.cloudbees/workflows/deployer.yaml
    vars: inherit
    secrets: inherit
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  STAGING:
    environment: STAGING
    uses: ./.cloudbees/workflows/deployer.yaml
    vars: inherit
    secrets: inherit
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
    needs: Approve
  PROD:
    needs: STAGING
    environment: PROD
    uses: ./.cloudbees/workflows/deployer.yaml
    vars: inherit
    secrets: inherit
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  Approve:
    needs: DEV
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
      approvers: Admins (System)
      approvalInputs: |
        Comment:
          type: string
